version: '3.8'
networks:
    app-tier:
        driver: bridge
services:
    database:
        image: mysql:latest
        container_name: database
        command: 
            --default-authentication-plugin=mysql_native_password 
            --init-file /init.sql
        volumes:
        - "./.mysql-data/db:/var/lib/mysql"
        - ./init.sql:/init.sql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database1
        ports: 
            - 3306:3306
        networks:
            - app-tier 
    app:
        container_name: app
        build: 
            context: .
            dockerfile: DockerFile
        command: bash -c 'while !</dev/tcp/database/3306; do sleep 1; done; npm run dev'
        ports: 
            - 3000:3000
        networks:
            - app-tier 
        volumes: 
            - .:/app
            - '/app/node_modules'
        depends_on: 
            - database