FROM node:12

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

VOLUME [ "/app/node_modules" ]

RUN apk update && apk add bash 

# CMD ["npm", "run", "dev"]

CMD /wait-for-it.sh database:3306 -- npm run dev